### PR TITLE
Misc cmake updates

### PR DESCRIPTION
**Pull request by chuckatkins**
A set of CMake updates for handling PIC options and a few OpenMP things.

### CODE REVIEW

**Comment by chuckatkins** [comment]
Looks like I need to fix a few issues with CMake version compatibility on Travis.  I'll update the upstream FindOpenMP.cmake backport accordingly.

**Comment by chuckatkins** [comment]
Found a few issues.  I'll close this until I can address them all

**Comment by salasoom** [comment]
When you open the new PR, can you base it off of the develop branch? Thanks.

**Comment by chuckatkins** [comment]
Sure thing!

**Pull request closed without merging**
