### PR TITLE
Fix RuntimeError using int64 in zfpy on Windows

### PR DESCRIPTION
**Pull request by cgohlke**
Thank you for releasing ZFP 0.5.5 with Python bindings!

I built zfpy-0.5.5 on Windows for Python 3.x without problems.

This PR fixes two test errors of type `RuntimeError: Item size 8 for PEP 3118 buffer format string l does not match the dtype l item size 4`. The reason for the failures is that, on Windows, the `C long` type is 4 bytes only.

~~The proposed fix works on Python >=3.3 only. But then, Python 2.7 will no longer be maintained from next year on, and zfp-0.5.5 does not build with Visual Studio 2008 (required for Python 2.7 compatibility on Windows) without code changes.~~

Btw, if you have not done so, you may want to register the name `zfpy` on [PyPI](https://pypi.org) before someone squats the name.

```
================================================= test session starts =================================================
platform win32 -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
<snip>
collected 5 items

..\test_numpy.py ...FF                                                                                           [100%]

====================================================== FAILURES =======================================================
___________________________________________ TestNumpy.test_different_dtypes ___________________________________________

self = <zfpy.test_numpy.TestNumpy testMethod=test_different_dtypes>

    def test_different_dtypes(self):
        shape = (5, 5)
        num_elements = shape[0] * shape[1]

        for dtype in [np.float32, np.float64]:
            elements = np.random.random_sample(num_elements)
            elements = elements.astype(dtype, casting="same_kind")
            array = np.reshape(elements, newshape=shape)
            self.lossless_round_trip(array)

        if (version_parse is not None and
            (version_parse(np.__version__) >= version_parse("1.11.0"))
        ):
            for dtype in [np.int32, np.int64]:
                array = np.random.randint(2**30, size=shape, dtype=dtype)
>               self.lossless_round_trip(array)

X:\Python37\lib\site-packages\zfpy\test_numpy.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
X:\Python37\lib\site-packages\zfpy\test_numpy.py:17: in lossless_round_trip
    decompressed_array = zfpy.decompress_numpy(compressed_array)
zfpy\zfpy.pyx:331: in zfpy.zfpy.decompress_numpy
    ???
zfpy\zfpy.pyx:349: in zfpy.zfpy.decompress_numpy
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = <[AttributeError("'zfpy.zfpy.memoryview' object has no attribute 'typecode'") raised in repr()] SafeRepr object at 0x227160bb390>
dtype = None, order = None

    def asarray(a, dtype=None, order=None):
        """Convert the input to an array.

        Parameters
        ----------
        a : array_like
            Input data, in any form that can be converted to an array.  This
            includes lists, lists of tuples, tuples, tuples of tuples, tuples
            of lists and ndarrays.
        dtype : data-type, optional
            By default, the data-type is inferred from the input data.
        order : {'C', 'F'}, optional
            Whether to use row-major (C-style) or
            column-major (Fortran-style) memory representation.
            Defaults to 'C'.

        Returns
        -------
        out : ndarray
            Array interpretation of `a`.  No copy is performed if the input
            is already an ndarray with matching dtype and order.  If `a` is a
            subclass of ndarray, a base class ndarray is returned.

        See Also
        --------
        asanyarray : Similar function which passes through subclasses.
        ascontiguousarray : Convert input to a contiguous array.
        asfarray : Convert input to a floating point ndarray.
        asfortranarray : Convert input to an ndarray with column-major
                         memory order.
        asarray_chkfinite : Similar function which checks input for NaNs and Infs.
        fromiter : Create an array from an iterator.
        fromfunction : Construct an array by executing a function on grid
                       positions.

        Examples
        --------
        Convert a list into an array:

        >>> a = [1, 2]
        >>> np.asarray(a)
        array([1, 2])

        Existing arrays are not copied:

        >>> a = np.array([1, 2])
        >>> np.asarray(a) is a
        True

        If `dtype` is set, array is copied only if dtype does not match:

        >>> a = np.array([1, 2], dtype=np.float32)
        >>> np.asarray(a, dtype=np.float32) is a
        True
        >>> np.asarray(a, dtype=np.float64) is a
        False

        Contrary to `asanyarray`, ndarray subclasses are not passed through:

        >>> issubclass(np.recarray, np.ndarray)
        True
        >>> a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
        >>> np.asarray(a) is a
        False
        >>> np.asanyarray(a) is a
        True

        """
>       return array(a, dtype, copy=False, order=order)
E       RuntimeError: Item size 8 for PEP 3118 buffer format string l does not match the dtype l item size 4.

X:\Python37\lib\site-packages\numpy\core\numeric.py:501: RuntimeError
________________________________________________ TestNumpy.test_utils _________________________________________________

self = <zfpy.test_numpy.TestNumpy testMethod=test_utils>

    def test_utils(self):
        for ndims in range(1, 5):
            for ztype, ztype_str in [
                    (zfpy.type_float,  "float"),
                    (zfpy.type_double, "double"),
                    (zfpy.type_int32,  "int32"),
                    (zfpy.type_int64,  "int64"),
            ]:
                orig_random_array = test_utils.getRandNumpyArray(ndims, ztype)
                orig_checksum = test_utils.getChecksumOrigArray(ndims, ztype)
                actual_checksum = test_utils.hashNumpyArray(orig_random_array)
                self.assertEqual(orig_checksum, actual_checksum)

                for stride_str, stride_config in [
                        ("as_is", test_utils.stride_as_is),
                        ("permuted", test_utils.stride_permuted),
                        ("interleaved", test_utils.stride_interleaved),
                        #("reversed", test_utils.stride_reversed),
                ]:
                    # permuting a 1D array is not supported
                    if stride_config == test_utils.stride_permuted and ndims == 1:
                        continue
                    random_array = test_utils.generateStridedRandomNumpyArray(
                        stride_config,
                        orig_random_array
                    )
                    self.assertTrue(np.equal(orig_random_array, random_array).all())

                    for compress_param_num in range(3):
                        modes = [(zfpy.mode_fixed_accuracy, "tolerance"),
                                 (zfpy.mode_fixed_precision, "precision"),
                                 (zfpy.mode_fixed_rate, "rate")]
                        if ztype in [zfpy.type_int32, zfpy.type_int64]:
                            modes = [modes[-1]] # only fixed-rate is supported for integers
                        for mode, mode_str in modes:
                            # Compression
                            compression_kwargs = {
                                mode_str: test_utils.computeParameterValue(
                                    mode,
                                    compress_param_num
                                ),
                            }

                            compressed_array = zfpy.compress_numpy(
                                random_array,
                                write_header=False,
                                **compression_kwargs
                            )
                            compressed_checksum = test_utils.getChecksumCompArray(
                                ndims,
                                ztype,
                                mode,
                                compress_param_num
                            )
                            actual_checksum = test_utils.hashCompressedArray(
                                compressed_array
                            )
                            self.assertEqual(compressed_checksum, actual_checksum)

                            # Decompression
                            decompressed_checksum = test_utils.getChecksumDecompArray(
                                ndims,
                                ztype,
                                mode,
                                compress_param_num
                            )

                            # Decompression using the "public" interface
                            # requires a header, so re-compress with the header
                            # included in the stream
                            compressed_array = zfpy.compress_numpy(
                                random_array,
                                write_header=True,
                                **compression_kwargs
                            )
                            decompressed_array = zfpy.decompress_numpy(
>                               compressed_array,
                            )

X:\Python37\lib\site-packages\zfpy\test_numpy.py:183:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
zfpy\zfpy.pyx:331: in zfpy.zfpy.decompress_numpy
    ???
zfpy\zfpy.pyx:349: in zfpy.zfpy.decompress_numpy
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = <[AttributeError("'zfpy.zfpy.memoryview' object has no attribute 'typecode'") raised in repr()] SafeRepr object at 0x227160b5b38>
dtype = None, order = None

    def asarray(a, dtype=None, order=None):
        """Convert the input to an array.

        Parameters
        ----------
        a : array_like
            Input data, in any form that can be converted to an array.  This
            includes lists, lists of tuples, tuples, tuples of tuples, tuples
            of lists and ndarrays.
        dtype : data-type, optional
            By default, the data-type is inferred from the input data.
        order : {'C', 'F'}, optional
            Whether to use row-major (C-style) or
            column-major (Fortran-style) memory representation.
            Defaults to 'C'.

        Returns
        -------
        out : ndarray
            Array interpretation of `a`.  No copy is performed if the input
            is already an ndarray with matching dtype and order.  If `a` is a
            subclass of ndarray, a base class ndarray is returned.

        See Also
        --------
        asanyarray : Similar function which passes through subclasses.
        ascontiguousarray : Convert input to a contiguous array.
        asfarray : Convert input to a floating point ndarray.
        asfortranarray : Convert input to an ndarray with column-major
                         memory order.
        asarray_chkfinite : Similar function which checks input for NaNs and Infs.
        fromiter : Create an array from an iterator.
        fromfunction : Construct an array by executing a function on grid
                       positions.

        Examples
        --------
        Convert a list into an array:

        >>> a = [1, 2]
        >>> np.asarray(a)
        array([1, 2])

        Existing arrays are not copied:

        >>> a = np.array([1, 2])
        >>> np.asarray(a) is a
        True

        If `dtype` is set, array is copied only if dtype does not match:

        >>> a = np.array([1, 2], dtype=np.float32)
        >>> np.asarray(a, dtype=np.float32) is a
        True
        >>> np.asarray(a, dtype=np.float64) is a
        False

        Contrary to `asanyarray`, ndarray subclasses are not passed through:

        >>> issubclass(np.recarray, np.ndarray)
        True
        >>> a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
        >>> np.asarray(a) is a
        False
        >>> np.asanyarray(a) is a
        True

        """
>       return array(a, dtype, copy=False, order=order)
E       RuntimeError: Item size 8 for PEP 3118 buffer format string l does not match the dtype l item size 4.

X:\Python37\lib\site-packages\numpy\core\numeric.py:501: RuntimeError
========================================= 2 failed, 3 passed in 7.74 seconds ==========================================
```

### CODE REVIEW

**Comment by cgohlke** [comment]
I think the patch should also work on Python 2, since the C/Cython buffer/view format string is in `struct`, not `array`, format <https://docs.python.org/2/library/struct.html#format-characters>

**Comment by lindstro** [comment]
@cgohlke Thanks for the PR.  zfPy has been tested only on Linux and macOS, which is why we didn't catch this.  We're in the process of setting up our Python tests on AppVeyor and will return to this PR when that's done.

One concern I have is compatibility with Python 2, which supposedly does not support the 'q' (long long) format.  Although this may be less of an issue on Windows, it is a concern on Linux and macOS.  On the other hand, the tests do pass on Travis with your proposed changes, so maybe my concerns are unfounded.

**Comment by salasoom** [comment]
@cgohlke I was able to setup the Python environment (2.7.16) on my Windows VM, reproduce the test error, and verify your fix works. However, I had to manually move some files to do so. Did you build the project through CMake command line? And it worked out-of-the-box?

Using a Python virtualenv, I was able to build and compile a Release version of zfp. Then running the test via `ctest` produced an `ImportError`, that the module `zfpy` could not be found. I got around this by copying `zfpy.pyd, test_utils.pyd`, and all `.dll` files into `tests/python`, where the test itself resides.

**Comment by cgohlke** [comment]
> Did you build the project through CMake command line? And it worked out-of-the-box?

I built static `zfp.lib` with CMake and Visual Studio 2015 or 2007 without problems.  Visual Studio 2008, required for Python 2.7 on Windows, doesn't work out-of-the-box because of some variables that are not defined at the beginning of scopes. For the Python bindings, I compiled `zfpy.pyx` (and optional `test_utils.pyx`) using a simple [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html) `setup.py` script which links to the static `zfp.lib`.

**Comment by lindstro** [comment]
> Visual Studio 2008, required for Python 2.7 on Windows, doesn't work out-of-the-box because of some variables that are not defined at the beginning of scopes.

Are these issues with the zfp C code?  If so, would you mind pointing them out?  I thought we had caught all of these in the latest release.

**Comment by cgohlke** [comment]
> Are these issues with the zfp C code?

I'm using this patch for building the static lib with Visual Studio 2008. I think there's more in the tests but I did not bother.

```diff
diff --git a/src/template/decodef.c b/src/template/decodef.c
index 5df1563..a32bdfb 100644
--- a/src/template/decodef.c
+++ b/src/template/decodef.c
@@ -6,14 +6,15 @@ static uint _t2(rev_decode_block, Scalar, DIMS)(zfp_stream* zfp, Scalar* fblock)
 static uint
 _t2(decode_block, Scalar, DIMS)(zfp_stream* zfp, Scalar* fblock)
 {
+  int emax, maxprec;
   uint bits = 1;
   /* test if block has nonzero values */
   if (stream_read_bit(zfp->stream)) {
     cache_align_(Int iblock[BLOCK_SIZE]);
     /* decode common exponent */
     bits += EBITS;
-    int emax = (int)stream_read_bits(zfp->stream, EBITS) - EBIAS;
-    int maxprec = precision(emax, zfp->maxprec, zfp->minexp, DIMS);
+    emax = (int)stream_read_bits(zfp->stream, EBITS) - EBIAS;
+    maxprec = precision(emax, zfp->maxprec, zfp->minexp, DIMS);
     /* decode integer block */
     bits += _t2(decode_block, Int, DIMS)(zfp->stream, zfp->minbits - bits, zfp->maxbits - bits, maxprec, iblock);
     /* perform inverse block-floating-point transform */
diff --git a/src/template/ompcompress.c b/src/template/ompcompress.c
index b0f86d2..32bd517 100644
--- a/src/template/ompcompress.c
+++ b/src/template/ompcompress.c
@@ -4,6 +4,8 @@
 static void
 _t2(compress_omp, Scalar, 1)(zfp_stream* stream, const zfp_field* field)
 {
+  int chunk;
+
   /* array metadata */
   const Scalar* data = (const Scalar*)field->data;
   uint nx = field->nx;
@@ -19,7 +21,6 @@ _t2(compress_omp, Scalar, 1)(zfp_stream* stream, const zfp_field* field)
     return;

   /* compress chunks of blocks in parallel */
-  int chunk;
   #pragma omp parallel for num_threads(threads)
   for (chunk = 0; chunk < (int)chunks; chunk++) {
     /* determine range of block indices assigned to this thread */
@@ -51,6 +52,8 @@ _t2(compress_omp, Scalar, 1)(zfp_stream* stream, const zfp_field* field)
 static void
 _t2(compress_strided_omp, Scalar, 1)(zfp_stream* stream, const zfp_field* field)
 {
+  int chunk;
+
   /* array metadata */
   const Scalar* data = (const Scalar*)field->data;
   uint nx = field->nx;
@@ -67,7 +70,6 @@ _t2(compress_strided_omp, Scalar, 1)(zfp_stream* stream, const zfp_field* field)
     return;

   /* compress chunks of blocks in parallel */
-  int chunk;
   #pragma omp parallel for num_threads(threads)
   for (chunk = 0; chunk < (int)chunks; chunk++) {
     /* determine range of block indices assigned to this thread */
@@ -99,6 +101,7 @@ _t2(compress_strided_omp, Scalar, 1)(zfp_stream* stream, const zfp_field* field)
 static void
 _t2(compress_strided_omp, Scalar, 2)(zfp_stream* stream, const zfp_field* field)
 {
+  int chunk;
   /* array metadata */
   const Scalar* data = (const Scalar*)field->data;
   uint nx = field->nx;
@@ -119,7 +122,6 @@ _t2(compress_strided_omp, Scalar, 2)(zfp_stream* stream, const zfp_field* field)
     return;

   /* compress chunks of blocks in parallel */
-  int chunk;
   #pragma omp parallel for num_threads(threads)
   for (chunk = 0; chunk < (int)chunks; chunk++) {
     /* determine range of block indices assigned to this thread */
@@ -154,6 +156,8 @@ _t2(compress_strided_omp, Scalar, 2)(zfp_stream* stream, const zfp_field* field)
 static void
 _t2(compress_strided_omp, Scalar, 3)(zfp_stream* stream, const zfp_field* field)
 {
+  int chunk;
+
   /* array metadata */
   const Scalar* data = (const Scalar*)field->data;
   uint nx = field->nx;
@@ -177,7 +181,6 @@ _t2(compress_strided_omp, Scalar, 3)(zfp_stream* stream, const zfp_field* field)
     return;

   /* compress chunks of blocks in parallel */
-  int chunk;
   #pragma omp parallel for num_threads(threads)
   for (chunk = 0; chunk < (int)chunks; chunk++) {
     /* determine range of block indices assigned to this thread */
@@ -213,6 +216,7 @@ _t2(compress_strided_omp, Scalar, 3)(zfp_stream* stream, const zfp_field* field)
 static void
 _t2(compress_strided_omp, Scalar, 4)(zfp_stream* stream, const zfp_field* field)
 {
+  int chunk;
   /* array metadata */
   const Scalar* data = field->data;
   uint nx = field->nx;
@@ -239,7 +243,6 @@ _t2(compress_strided_omp, Scalar, 4)(zfp_stream* stream, const zfp_field* field)
     return;

   /* compress chunks of blocks in parallel */
-  int chunk;
   #pragma omp parallel for num_threads(threads)
   for (chunk = 0; chunk < (int)chunks; chunk++) {
     /* determine range of block indices assigned to this thread */
diff --git a/src/template/revdecodef.c b/src/template/revdecodef.c
index 221a4b2..2a5da6e 100644
--- a/src/template/revdecodef.c
+++ b/src/template/revdecodef.c
@@ -21,6 +21,7 @@ _t1(rev_inv_reinterpret, Scalar)(Int* iblock, Scalar* fblock, uint n)
 static uint
 _t2(rev_decode_block, Scalar, DIMS)(zfp_stream* zfp, Scalar* fblock)
 {
+  int emax;
   uint bits = 0;
   cache_align_(Int iblock[BLOCK_SIZE]);
   /* test whether block is all-zero */
@@ -37,7 +38,7 @@ _t2(rev_decode_block, Scalar, DIMS)(zfp_stream* zfp, Scalar* fblock)
     else {
       /* decode common exponent */
       bits += EBITS;
-      int emax = (int)stream_read_bits(zfp->stream, EBITS) - EBIAS;
+      emax = (int)stream_read_bits(zfp->stream, EBITS) - EBIAS;
       /* decode integer block */
       bits += _t2(rev_decode_block, Int, DIMS)(zfp->stream, zfp->minbits - bits, zfp->maxbits - bits, iblock);
       /* perform inverse block-floating-point transform */
```

**Comment by lindstro** [comment]
Thanks for the patch.  I've fixed these declaration issues (minus the tests) on `develop`.  Somehow this wasn't caught by our more stringent tests.  We're still working on getting zfPy built on Windows.

**Comment by salasoom** [comment]
@cgohlke We now have zfpy up and running on Appveyor, for MSVC builds. And we see the runtime error you are getting. Can you pull in the latest code on the develop branch, with your commits coming after?

**Comment by cgohlke** [comment]
> Can you pull in the latest code on the develop branch, with your commits coming after?

I no longer have the repository to make changes to this PR. Probably best to make a new PR.

**Comment by salasoom** [comment]
Since the host code doesn't exist anymore, I've cherry-picked this commit into develop https://github.com/LLNL/zfp/commit/f76320231734aaa9ae5535cb9a7cd478507e8d25

**Pull request closed without merging**
