### PR TITLE
Add CMake configuration and continuous integration support

### PR DESCRIPTION
**Pull request by estan**
This is a first stab at adding CMake as a build system.

The knobs in `Config` have been turned into CMake options (`option(..)`). I also took the liberty of having both a shared and a static library built by default, while letting the user turn of building of one or the other with `-DBUILD_SHARED=OFF` or `-DBUILD_STATIC=OFF`.

Here's me configuring, building, running the tests and installing to `~/zfp-inst` on my Ubuntu 16.04 laptop:

```
estan@newton:~/zfp$ mkdir build
estan@newton:~/zfp$ cd build
estan@newton:~/zfp/build$ cmake -DCMAKE_INSTALL_PREFIX=~/zfp-inst ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test C_COMPILER_SUPPORTS_WALL
-- Performing Test C_COMPILER_SUPPORTS_WALL - Success
-- Performing Test C_COMPILER_SUPPORTS_WNO_UNUSED_FUNCTION
-- Performing Test C_COMPILER_SUPPORTS_WNO_UNUSED_FUNCTION - Success
-- Performing Test CXX_COMPILER_SUPPORTS_WALL
-- Performing Test CXX_COMPILER_SUPPORTS_WALL - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/estan/zfp/build
estan@newton:~/zfp/build$ make
Scanning dependencies of target zfp_static
[  2%] Building C object src/CMakeFiles/zfp_static.dir/bitstream.c.o
[  4%] Building C object src/CMakeFiles/zfp_static.dir/decode1d.c.o
[  6%] Building C object src/CMakeFiles/zfp_static.dir/decode1f.c.o
[  8%] Building C object src/CMakeFiles/zfp_static.dir/decode2d.c.o
[ 11%] Building C object src/CMakeFiles/zfp_static.dir/decode2f.c.o
[ 13%] Building C object src/CMakeFiles/zfp_static.dir/decode3d.c.o
[ 15%] Building C object src/CMakeFiles/zfp_static.dir/decode3f.c.o
[ 17%] Building C object src/CMakeFiles/zfp_static.dir/encode1d.c.o
[ 20%] Building C object src/CMakeFiles/zfp_static.dir/encode1f.c.o
[ 22%] Building C object src/CMakeFiles/zfp_static.dir/encode2d.c.o
[ 24%] Building C object src/CMakeFiles/zfp_static.dir/encode2f.c.o
[ 26%] Building C object src/CMakeFiles/zfp_static.dir/encode3d.c.o
[ 28%] Building C object src/CMakeFiles/zfp_static.dir/encode3f.c.o
[ 31%] Building C object src/CMakeFiles/zfp_static.dir/zfp.c.o
[ 33%] Linking C static library libzfp.a
[ 33%] Built target zfp_static
Scanning dependencies of target zfp_shared
[ 35%] Building C object src/CMakeFiles/zfp_shared.dir/bitstream.c.o
[ 37%] Building C object src/CMakeFiles/zfp_shared.dir/decode1d.c.o
[ 40%] Building C object src/CMakeFiles/zfp_shared.dir/decode1f.c.o
[ 42%] Building C object src/CMakeFiles/zfp_shared.dir/decode2d.c.o
[ 44%] Building C object src/CMakeFiles/zfp_shared.dir/decode2f.c.o
[ 46%] Building C object src/CMakeFiles/zfp_shared.dir/decode3d.c.o
[ 48%] Building C object src/CMakeFiles/zfp_shared.dir/decode3f.c.o
[ 51%] Building C object src/CMakeFiles/zfp_shared.dir/encode1d.c.o
[ 53%] Building C object src/CMakeFiles/zfp_shared.dir/encode1f.c.o
[ 55%] Building C object src/CMakeFiles/zfp_shared.dir/encode2d.c.o
[ 57%] Building C object src/CMakeFiles/zfp_shared.dir/encode2f.c.o
[ 60%] Building C object src/CMakeFiles/zfp_shared.dir/encode3d.c.o
[ 62%] Building C object src/CMakeFiles/zfp_shared.dir/encode3f.c.o
[ 64%] Building C object src/CMakeFiles/zfp_shared.dir/zfp.c.o
[ 66%] Linking C shared library libzfp.so
[ 66%] Built target zfp_shared
Scanning dependencies of target simple
[ 68%] Building C object examples/CMakeFiles/simple.dir/simple.c.o
[ 71%] Linking C executable simple
[ 71%] Built target simple
Scanning dependencies of target pgm
[ 73%] Building C object examples/CMakeFiles/pgm.dir/pgm.c.o
[ 75%] Linking C executable pgm
[ 75%] Built target pgm
Scanning dependencies of target diffusion-zfp
[ 77%] Building CXX object examples/CMakeFiles/diffusion-zfp.dir/diffusion.cpp.o
[ 80%] Linking CXX executable diffusion-zfp
[ 80%] Built target diffusion-zfp
Scanning dependencies of target diffusion-raw
[ 82%] Building CXX object examples/CMakeFiles/diffusion-raw.dir/diffusion.cpp.o
[ 84%] Linking CXX executable diffusion-raw
[ 84%] Built target diffusion-raw
Scanning dependencies of target zfp-bin
[ 86%] Building C object examples/CMakeFiles/zfp-bin.dir/zfp.c.o
[ 88%] Linking C executable zfp
[ 88%] Built target zfp-bin
Scanning dependencies of target speed
[ 91%] Building C object examples/CMakeFiles/speed.dir/speed.c.o
[ 93%] Linking C executable speed
[ 93%] Built target speed
Scanning dependencies of target testzfp
[ 95%] Building CXX object examples/CMakeFiles/testzfp.dir/testzfp.cpp.o
[ 97%] Building C object examples/CMakeFiles/testzfp.dir/fields.c.o
[100%] Linking CXX executable testzfp
[100%] Built target testzfp
estan@newton:~/zfp/build$ ctest -V
UpdateCTestConfiguration  from :/home/estan/zfp/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/estan/zfp/build/DartConfiguration.tcl
Test project /home/estan/zfp/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: testzfp

1: Test command: /home/estan/zfp/build/examples/testzfp
1: Test timeout computed to be: 9.99988e+06
1: testing 1D array of floats
1:   compress:   rate= 2                                                    OK 
1:   decompress: rate= 2 1.997e+00 <= 1.998e+00                             OK 
1:   compress:   rate= 8                                                    OK 
1:   decompress: rate= 8 7.766e-03 <= 7.767e-03                             OK 
1:   compress:   rate=32                                                    OK 
1:   decompress: rate=32 0.000e+00 <= 0.000e+00                             OK 
1:   compress:   precision= 4 ratio=  7.529                                 OK 
1:   decompress: precision= 4                                               OK 
1:   compress:   precision= 8 ratio=  5.032                                 OK 
1:   decompress: precision= 8                                               OK 
1:   compress:   precision=16 ratio=  2.612                                 OK 
1:   decompress: precision=16                                               OK 
1:   compress:   tolerance=9.766e-04 ratio=  3.448                          OK 
1:   decompress: tolerance=9.766e-04 4.047e-04 <= 9.766e-04                 OK 
1:   compress:   tolerance=2.384e-07 ratio=  1.609                          OK 
1:   decompress: tolerance=2.384e-07 1.192e-07 <= 2.384e-07                 OK 
1:   compress:   tolerance=0.000e+00 ratio=  1.154                          OK 
1:   decompress: tolerance=0.000e+00 0.000e+00 <= 0.000e+00                 OK 
1:   construct:  0.000e+00 <= 0.000e+00                                     OK 
1:   update:     4.385e-03 ~ 4.385e-03                                      OK 
1: 
1: testing 2D array of floats
1:   compress:   rate= 2                                                    OK 
1:   decompress: rate= 2 2.356e-01 <= 2.356e-01                             OK 
1:   compress:   rate= 8                                                    OK 
1:   decompress: rate= 8 3.939e-04 <= 3.939e-04                             OK 
1:   compress:   rate=32                                                    OK 
1:   decompress: rate=32 7.451e-09 <= 7.451e-09                             OK 
1:   compress:   precision= 4 ratio= 28.444                                 OK 
1:   decompress: precision= 4                                               OK 
1:   compress:   precision= 8 ratio= 12.642                                 OK 
1:   decompress: precision= 8                                               OK 
1:   compress:   precision=16 ratio=  3.961                                 OK 
1:   decompress: precision=16                                               OK 
1:   compress:   tolerance=9.766e-04 ratio=  5.611                          OK 
1:   decompress: tolerance=9.766e-04 2.423e-04 <= 9.766e-04                 OK 
1:   compress:   tolerance=2.384e-07 ratio=  1.879                          OK 
1:   decompress: tolerance=2.384e-07 7.916e-08 <= 2.384e-07                 OK 
1:   compress:   tolerance=0.000e+00 ratio=  1.341                          OK 
1:   decompress: tolerance=0.000e+00 (7.451e-09 > 0)                        OK 
1:   construct:  7.451e-09 <= 7.451e-09                                     OK 
1:   update:     9.260e-02 ~ 9.260e-02                                      OK 
1: 
1: testing 3D array of floats
1:   compress:   rate= 2                                                    OK 
1:   decompress: rate= 2 2.478e-01 <= 2.479e-01                             OK 
1:   compress:   rate= 8                                                    OK 
1:   decompress: rate= 8 1.524e-03 <= 1.525e-03                             OK 
1:   compress:   rate=32                                                    OK 
1:   decompress: rate=32 7.451e-08 <= 7.451e-08                             OK 
1:   compress:   precision= 4 ratio=128.000                                 OK 
1:   decompress: precision= 4                                               OK 
1:   compress:   precision= 8 ratio= 22.756                                 OK 
1:   decompress: precision= 8                                               OK 
1:   compress:   precision=16 ratio=  4.000                                 OK 
1:   decompress: precision=16                                               OK 
1:   compress:   tolerance=9.766e-04 ratio=  3.842                          OK 
1:   decompress: tolerance=9.766e-04 1.855e-04 <= 9.766e-04                 OK 
1:   compress:   tolerance=2.384e-07 ratio=  1.574                          OK 
1:   decompress: tolerance=2.384e-07 7.451e-08 <= 2.384e-07                 OK 
1:   compress:   tolerance=0.000e+00 ratio=  1.334                          OK 
1:   decompress: tolerance=0.000e+00 (7.451e-08 > 0)                        OK 
1:   construct:  7.451e-08 <= 7.451e-08                                     OK 
1:   update:     3.760e-01 ~ 3.760e-01                                      OK 
1: 
1: testing 1D array of doubles
1:   compress:   rate= 3                                                    OK 
1:   decompress: rate= 3 1.997e+00 <= 1.998e+00                             OK 
1:   compress:   rate= 4                                                    OK 
1:   decompress: rate= 4 9.975e-01 <= 9.976e-01                             OK 
1:   compress:   rate=16                                                    OK 
1:   decompress: rate=16 1.359e-05 <= 1.360e-05                             OK 
1:   compress:   rate=64                                                    OK 
1:   decompress: rate=64 0.000e+00 <= 0.000e+00                             OK 
1:   compress:   precision= 8 ratio=  9.002                                 OK 
1:   decompress: precision= 8                                               OK 
1:   compress:   precision=16 ratio=  4.923                                 OK 
1:   decompress: precision=16                                               OK 
1:   compress:   precision=32 ratio=  2.248                                 OK 
1:   decompress: precision=32                                               OK 
1:   compress:   tolerance=9.766e-04 ratio=  6.380                          OK 
1:   decompress: tolerance=9.766e-04 4.047e-04 <= 9.766e-04                 OK 
1:   compress:   tolerance=4.441e-16 ratio=  1.289                          OK 
1:   decompress: tolerance=4.441e-16 0.000e+00 <= 4.441e-16                 OK 
1:   compress:   tolerance=0.000e+00 ratio=  1.058                          OK 
1:   decompress: tolerance=0.000e+00 0.000e+00 <= 0.000e+00                 OK 
1:   construct:  2.353e-10 <= 2.354e-10                                     OK 
1:   update:     4.385e-03 ~ 4.385e-03                                      OK 
1: 
1: testing 2D array of doubles
1:   compress:   rate= 1                                                    OK 
1:   decompress: rate= 1 2.944e+00 <= 2.944e+00                             OK 
1:   compress:   rate= 4                                                    OK 
1:   decompress: rate= 4 2.491e-02 <= 2.491e-02                             OK 
1:   compress:   rate=16                                                    OK 
1:   decompress: rate=16 2.577e-06 <= 2.578e-06                             OK 
1:   compress:   rate=64                                                    OK 
1:   decompress: rate=64 0.000e+00 <= 0.000e+00                             OK 
1:   compress:   precision= 8 ratio= 23.540                                 OK 
1:   decompress: precision= 8                                               OK 
1:   compress:   precision=16 ratio=  7.743                                 OK 
1:   decompress: precision=16                                               OK 
1:   compress:   precision=32 ratio=  2.661                                 OK 
1:   decompress: precision=32                                               OK 
1:   compress:   tolerance=9.766e-04 ratio= 10.865                          OK 
1:   decompress: tolerance=9.766e-04 2.423e-04 <= 9.766e-04                 OK 
1:   compress:   tolerance=4.441e-16 ratio=  1.385                          OK 
1:   decompress: tolerance=4.441e-16 0.000e+00 <= 4.441e-16                 OK 
1:   compress:   tolerance=0.000e+00 ratio=  1.142                          OK 
1:   decompress: tolerance=0.000e+00 0.000e+00 <= 0.000e+00                 OK 
1:   construct:  5.731e-09 <= 5.731e-09                                     OK 
1:   update:     9.260e-02 ~ 9.260e-02                                      OK 
1: 
1: testing 3D array of doubles
1:   compress:   rate= 1                                                    OK 
1:   decompress: rate= 1 6.102e-01 <= 6.103e-01                             OK 
1:   compress:   rate= 4                                                    OK 
1:   decompress: rate= 4 3.252e-02 <= 3.253e-02                             OK 
1:   compress:   rate=16                                                    OK 
1:   decompress: rate=16 6.466e-06 <= 6.467e-06                             OK 
1:   compress:   rate=64                                                    OK 
1:   decompress: rate=64 0.000e+00 <= 0.000e+00                             OK 
1:   compress:   precision= 8 ratio= 44.043                                 OK 
1:   decompress: precision= 8                                               OK 
1:   compress:   precision=16 ratio=  7.953                                 OK 
1:   decompress: precision=16                                               OK 
1:   compress:   precision=32 ratio=  2.663                                 OK 
1:   decompress: precision=32                                               OK 
1:   compress:   tolerance=9.766e-04 ratio=  7.642                          OK 
1:   decompress: tolerance=9.766e-04 1.855e-04 <= 9.766e-04                 OK 
1:   compress:   tolerance=4.441e-16 ratio=  1.296                          OK 
1:   decompress: tolerance=4.441e-16 0.000e+00 <= 4.441e-16                 OK 
1:   compress:   tolerance=0.000e+00 ratio=  1.142                          OK 
1:   decompress: tolerance=0.000e+00 0.000e+00 <= 0.000e+00                 OK 
1:   construct:  2.804e-08 <= 2.804e-08                                     OK 
1:   update:     3.760e-01 ~ 3.760e-01                                      OK 
1: 
1: all tests passed
1/1 Test #1: testzfp ..........................   Passed    0.04 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.04 sec
estan@newton:~/zfp/build$ make install
[ 33%] Built target zfp_static
[ 66%] Built target zfp_shared
[ 71%] Built target simple
[ 75%] Built target pgm
[ 80%] Built target diffusion-zfp
[ 84%] Built target diffusion-raw
[ 88%] Built target zfp-bin
[ 93%] Built target speed
[100%] Built target testzfp
Install the project...
-- Install configuration: "Release"
-- Installing: /home/estan/zfp-inst/lib/libzfp.so.0.5.0
-- Installing: /home/estan/zfp-inst/lib/libzfp.so.0
-- Installing: /home/estan/zfp-inst/lib/libzfp.so
-- Installing: /home/estan/zfp-inst/lib/libzfp.a
-- Installing: /home/estan/zfp-inst/include/zfp
-- Installing: /home/estan/zfp-inst/include/zfp/macros.h
-- Installing: /home/estan/zfp-inst/include/zfp/bitstream.h
-- Installing: /home/estan/zfp-inst/include/zfp/system.h
-- Installing: /home/estan/zfp-inst/include/zfp/zfp.h
-- Installing: /home/estan/zfp-inst/include/zfp/types.h
estan@newton:~/zfp/build$
```

Please try it out and tell me what you think.

I'm also adding a `.travis.yml` file for building/testing on Linux at Travis CI, and an `.appveyor.yml` for building/testing on Windows at Appveyor. You can see the latest builds at

    https://travis-ci.org/estan/zfp/builds/172655588

and

    https://ci.appveyor.com/project/estan/zfp

As you can see the MinGW build on Appveyor is currently failing, so that's something to investigate.

### CODE REVIEW

**Comment by chuckatkins** [comment]
Whoops, I just did this too.  I didn't even see this PR :-/, my mistake.  Would you be interested in melding our two branches?

**Comment by estan** [comment]
Ah, the more the merrier :) I don't mind if your branch is merged first. You seem to have been a bit more thorough than I with some things (turning examples/tests on/off, checking for in-source build, et.c.). So maybe best we merge yours first, and then I'll see if there was something I did that should be added as well.

Lets see what Peter says. I was in contact with him over e-mail a couple of weeks ago, asking if he had time to look at the PR, but he had been swamped.

**Comment by lindstro** [comment]
I am hoping to get to this PR and others in the next few weeks.  CMake has been on my to-do list, so I appreciate all the help with setting this up for zfp.


--
Peter Lindstrom . pl@llnl.gov<mailto:pl@llnl.gov> . http://people.llnl.gov/pl . 925-423-5925

________________________________

**Comment by estan** [comment]
I'm closing this since @chuckatkins is planning on an updated version of his PR. When that is merged, I'll create a new one with just the CI bits.

**Pull request closed without merging**
